spring.application.name=shiptrack-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shiptrack_db
spring.datasource.username=postgres
spring.datasource.password=Ash@1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=shiptrack-secret-key-2026-very-long-secret-key
jwt.expiration-ms=86400000