spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

geoapify.api.key=${GEOPIFY_API_KEY}

app.upload.dir=uploads
app.upload.base-url=${BACKEND_URL}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=25MB


google.client.id=${GOOGLE_CLIENT_ID}

app.frontend.url=${FRONTEND_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.from-number=${TWILIO_FROM_NUMBER}

server.error.include-message=always
server.error.include-binding-errors=always