spring.application.name=shiptrack-backend

server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shiptrack_db
spring.datasource.username=postgres
spring.datasource.password=raju

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT Configuration
# =========================
jwt.secret=ShipTrackSecretKeyForJWTAuthentication2026ShipTrackPro
jwt.expiration=86400000

# =========================
# Geoapify API
# =========================
geoapify.api.key=${GEOAPIFY_API_KEY:00536d2ffecb43498563818ceaf30650}
